#!/bin/bash

# text gambar
apt-get install boxes

# color text
cd
rm -rf /root/.bashrc
wget -O /root/.bashrc "https://raw.githubusercontent.com/fluxo7/m.e.n.u/master/method1/.bashrc"

# install lolcat
sudo apt-get -y install ruby
sudo gem install lolcat

# download script

cd
#cd
#wget -O /usr/bin/benchmark "https://raw.githubusercontent.com/redhatz91/menubahaya/master/benchmark.sh"
#wget -O /usr/bin/speedtest "https://raw.githubusercontent.com/redhatz91/menubahaya/master/speedtest_cli.py"
#wget -O /usr/bin/ps-mem "https://raw.githubusercontent.com/redhatz91/menubahaya/master/ps_mem.py"
#wget -O /etc/issue.net "https://raw.githubusercontent.com/redhatz91/menubahaya/master/bannerA"
#wget -O /usr/bin/dropmon "https://raw.githubusercontent.com/redhatz91/menubahaya/master/dropmon.sh"
#wget -O /usr/bin/menu "https://raw.githubusercontent.com/redhatz91/menubahaya/master/menu.sh"
#wget -O /usr/bin/user-active-list "https://raw.githubusercontent.com/redhatz91/menubahaya/master/user-active-list.sh"
#wget -O /usr/bin/user-add "https://raw.githubusercontent.com/redhatz91/menubahaya/master/user-add.sh"
#wget -O /usr/bin/user-add-pptp "https://raw.githubusercontent.com/redhatz91/menubahaya/master/user-add-pptp.sh"
#wget -O /usr/bin/user-del "https://raw.githubusercontent.com/redhatz91/menubahaya/master/user-del.sh"
#wget -O /usr/bin/disable-user-expire "https://raw.githubusercontent.com/redhatz91/menubahaya/master/disable-user-expire.sh"
#wget -O /usr/bin/delete-user-expire "https://raw.githubusercontent.com/redhatz91/menubahaya/master/delete-user-expire.sh"
#wget -O /usr/bin/banned-user "https://raw.githubusercontent.com/redhatz91/menubahaya/master/banned-user.sh"
#wget -O /usr/bin/unbanned-user https://raw.githubusercontent.com/elangoverdosis/deeniedoank/debian7/unbanned-user.sh"
#wget -O /usr/bin/user-expire-list "https://raw.githubusercontent.com/redhatz91/menubahaya/master/user-expire-list.sh"
#wget -O /usr/bin/user-gen "https://raw.githubusercontent.com/redhatz91/menubahaya/master/user-gen.sh"
#wget -O /usr/bin/user-limit "https://raw.githubusercontent.com/redhatz91/menubahaya/master/user-limit.sh"
#wget -O /usr/bin/user-list "https://raw.githubusercontent.com/redhatz91/menubahaya/master/user-list.sh"
#wget -O /usr/bin/user-login "https://raw.githubusercontent.com/redhatz91/menubahaya/master/user-login.sh"
#wget -O /usr/bin/user-pass "https://raw.githubusercontent.com/redhatz91/menubahaya/master/user-pass.sh"
#wget -O /usr/bin/user-renew "https://raw.githubusercontent.com/redhatz91/menubahaya/master/user-renew.sh"
#wget -O /usr/bin/clearcache.sh "https://raw.githubusercontent.com/redhatz91/menubahaya/master/clearcache.sh"
#wget -O /usr/bin/bannermenu "https://raw.githubusercontent.com/redhatz91/menubahaya/master/bannermenu"
wget -O /usr/bin/menu-update-script-vps.sh "https://raw.githubusercontent.com/redhatz91/menubahaya/master/menu-update-script-vps.sh"


#chmod +x /usr/bin/benchmark
#chmod +x /usr/bin/speedtest
#chmod +x /usr/bin/ps-mem
#chmod +x /usr/bin/dropmon
#chmod +x /usr/bin/menu
#chmod +x /usr/bin/user-active-list
#chmod +x /usr/bin/user-add
#chmod +x /usr/bin/user-add-pptp
#chmod +x /usr/bin/user-del
#chmod +x /usr/bin/disable-user-expire
#chmod +x /usr/bin/delete-user-expire
#chmod +x /usr/bin/banned-user
#chmod +x /usr/bin/unbanned-user
clear
#chmod +x /usr/bin/user-expire-list
#chmod +x /usr/bin/user-gen
#chmod +x /usr/bin/user-limit
#chmod +x /usr/bin/user-list
#chmod +x /usr/bin/user-login
#chmod +x /usr/bin/user-pass
#chmod +x /usr/bin/user-renew
#chmod +x /usr/bin/clearcache.sh
#chmod +x /usr/bin/bannermenu
chmod +x /usr/bin/menu-update-script-vps.sh
rm /usr/bin/updatescript.sh
clear
echo ""
echo ""
echo ""
echo "selesai bosss...." | lolcat

sleep 3
rm /root/IP
rm /root/IPcarding
clear
menu
